uploads = []
outputs = []

[[generated]]
id = "qOHwZ8XGIVcToMlHbODS_"
uri = "file://artifacts/horizone/src/assets/hero-car.png"
type = "image"
title = "Hero background image"

[[generated]]
id = "5EcKWNmNGzXkmp4IIvzuD"
uri = "file://artifacts/horizone/src/assets/car-suv.png"
type = "image"
title = "Placeholder SUV"

[[generated]]
id = "P11qt2lN0E2GJdFp4xDvr"
uri = "file://artifacts/horizone/src/assets/car-sedan.png"
type = "image"
title = "Placeholder Sedan"
